# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller standalone Windows specification for Ren'Py Inspector."""

from pathlib import Path

ROOT_DIR = Path(SPECPATH).resolve().parent if Path(SPECPATH).name == "scripts" else Path(SPECPATH).resolve()

# Collect submodules and hidden imports
hiddenimports = [
    "PySide6",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "renpy_inspector.cli.main",
    "renpy_inspector.gui.app",
    "renpy_inspector.gui.main_window",
    "renpy_inspector.gui.theme",
    "renpy_inspector.gui.worker",
    "renpy_inspector.gui.components.filter_bar",
    "renpy_inspector.gui.components.issue_details",
    "renpy_inspector.gui.components.issues_table",
    "renpy_inspector.gui.components.metric_cards",
    "renpy_inspector.gui.components.project_selector",
    "renpy_inspector.core.engine.analyzer",
    "renpy_inspector.core.engine.context",
    "renpy_inspector.core.engine.registry",
    "renpy_inspector.core.engine.runner",
    "renpy_inspector.core.license.manager",
    "renpy_inspector.core.license.tier",
    "renpy_inspector.core.models.analysis",
    "renpy_inspector.core.models.asset",
    "renpy_inspector.core.models.enums",
    "renpy_inspector.core.models.failures",
    "renpy_inspector.core.models.issue",
    "renpy_inspector.core.models.location",
    "renpy_inspector.core.models.project",
    "renpy_inspector.core.models.resolution",
    "renpy_inspector.core.models.symbols",
    "renpy_inspector.core.parser.action_extractor",
    "renpy_inspector.core.parser.errors",
    "renpy_inspector.core.parser.lexer",
    "renpy_inspector.core.parser.project_parser",
    "renpy_inspector.core.parser.result",
    "renpy_inspector.core.parser.rpy_parser",
    "renpy_inspector.core.parser.source",
    "renpy_inspector.core.plugins.loader",
    "renpy_inspector.core.reporting.html_reporter",
    "renpy_inspector.core.reporting.json_reporter",
    "renpy_inspector.core.scanner.asset_catalog",
    "renpy_inspector.core.scanner.file_scanner",
    "renpy_inspector.core.scanner.validator",
    "renpy_inspector.core.rules",
    "renpy_inspector.core.rules.base",
    "renpy_inspector.core.rules.assets",
    "renpy_inspector.core.rules.assets.case_mismatch",
    "renpy_inspector.core.rules.assets.invalid_audio_channel",
    "renpy_inspector.core.rules.assets.missing_audio",
    "renpy_inspector.core.rules.assets.missing_font",
    "renpy_inspector.core.rules.assets.missing_image",
    "renpy_inspector.core.rules.assets.unused_asset",
    "renpy_inspector.core.rules.code",
    "renpy_inspector.core.rules.code.broken_call",
    "renpy_inspector.core.rules.code.broken_jump",
    "renpy_inspector.core.rules.code.conflicting_define_default",
    "renpy_inspector.core.rules.code.define_persistent",
    "renpy_inspector.core.rules.code.duplicate_label",
    "renpy_inspector.core.rules.code.duplicate_screen",
    "renpy_inspector.core.rules.code.empty_menu",
    "renpy_inspector.core.rules.code.invalid_init_priority",
    "renpy_inspector.core.rules.code.shadow_builtin",
    "renpy_inspector.core.rules.code.unclosed_text_tags",
    "renpy_inspector.core.rules.code.undefined_screen",
    "renpy_inspector.core.rules.code.unreachable_code",
    "renpy_inspector.core.rules.code.unused_label",
    "renpy_inspector.core.rules.translation",
    "renpy_inspector.core.rules.translation.missing_translation",
]

block_cipher = None

a = Analysis(
    [str(ROOT_DIR / "renpy_inspector" / "gui" / "app.py")],
    pathex=[str(ROOT_DIR)],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="RenPyInspector",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
